### PR TITLE
allow individual styling in `multiBar.create()`

### PR DESCRIPTION
**Pull request by Araxeus**
on `multiBar.create()`, allow changing the following style options:
* `barCompleteChar`
* `barIncompleteChar`

Because I just wanted to have a top bar that is a general status, and the other ones are the running processes

gif

### CODE REVIEW

**Comment by AndiDittrich** [comment]
hi @Araxeus ,

thanks for your contribution. i can confirm the behaviour but like to prefer a more comprehensive solution: some more elements of the options initialization has to be moved into the `generic-bar` constructor. therefore i won't merge your request directly

btw. don't commit changes to meta files like `.gitignore`

**Comment by Araxeus** [comment]
> btw. don't commit changes to meta files like .gitignore

And why is that?

I'm using yarn v3 and installing creates a `.yarn` folder with dozens or hundreds of files

Without adding it to the `.gitignore` it becomes very painful to commit when I have hundreds of "tracked changes"

Also what reason would there ever be not to modify `.gitignore`? It's not like it changes the program in any way... Its literally here to make dev life easier

**Comment by AndiDittrich** [comment]
a pull request should only contain changes to required files..

**Comment by AndiDittrich** [comment]
added to 6c757400e632e52f209d1a932de7b29190493936

**Comment by Araxeus** [comment]
Anyways, thank you for merging the feature 🎉

**Comment by Araxeus** [comment]
And i also just wanted to say, if it was my first time contributing to open source, I dont think I would have been very encouraged by the fact that you "discarded" my work

It's not my first rodeo, so I understand where you're coming from, I'm just saying its not a very welcoming behavior

The first pull request I ever made was met with excitement and encouragement, which made continue on the open source path :)

Just food for thoughts @AndiDittrich

**Comment by AndiDittrich** [comment]
sry for this but on the other hand you've to understand that it's very time consuming to give everybody a crash course howto contribute, fix their first time mistakes etc. didn't have time for that...i know that the standard git workflow is complex for beginners.

fixing issues directly is much more efficient especially if other changes needs to be applied. so don't worry

**Pull request closed without merging**
